### ISSUE TITLE
how to set orig_shape

### ISSUE THREAD

**Issue by Cherished-l** [LangDaniel/MAEMI#2]
hi, i'm study your code
in main_pretrain.py, how to set orig_shape?
you don't give the para in the args.

thx!

**Comment by Cherished-l** [comment]
if the img size between pretrain and finetune is the same
maybe it interpolate_pos_embed does'nt work?

**Comment by LangDaniel** [comment]
Hi,
sorry, can you elaborate a bit more?
What are you aiming for?

Shape of the input batches in set by `shape` in `training/parameter/par.yml`.
Model input size is then hard encoded to have the same size in `training/train.py` and finetuning is assumed to have the same batch size a pretraining.
